GITROOT=$(shell git rev-parse --show-toplevel)
CXXFLAGS ?= -O3
CLOCK_TARGET_PS ?= 1000 # 1 GHz clock rate
GENERATOR_TYPE ?= pipeline
DELAY_MODEL ?= unit

NAME=donut
SRCS=donut.cc

include ${GITROOT}/common.mk
